### ISSUE TITLE
[Feature]: Laravel 12 compatibility

### ISSUE THREAD

**Issue by ilvalerione** [MaestroError/LarAgent#4]
### Feature Summary

Hi @MaestroError 
I tried to add the Laravel 12 compatibility, but the it seams I'm not able to make the tests works.

I changed the github action "run_test" flow with this: 

```yaml
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.4, 8.3]
        laravel: [11.*, 12.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench: 9.*
            carbon: ^2.63
            larastan: 2.*
          - laravel: 12.*
            testbench: 10.*
            carbon: 3.*
            larastan: 3.*
```

And updated the composer dependencies: https://github.com/ilvalerione/LarAgent/blob/main/composer.json

But the github action fails because it result in an incompatible set of packages. Maybe you are able to replicate this changes and make it run. 

### Use Case

extend compatibility for upcoming laravel applications upgrades

### Checklist

- [x] I checked for duplicate issues before submitting.
- [x] I am willing to help implement this feature if needed.
